"use client";
/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: TapmodStudio (https://sketchfab.com/TapmodStudio)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/batman-6e54eb66a143449d8101e2d2a092ead4
Title: Batman
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";
import { useFrame } from "@react-three/fiber";

export default function BatModel(props) {
  const { nodes, materials } = useGLTF("/models/scene-transformed.glb");
  const modelRef = useRef();
  useFrame((state, delta, xrFrame) => {
    modelRef.current.position.y = -1.5 +  Math.sin(state.clock.elapsedTime)*0.15;
  });
  return (
    <group
      {...props}
      dispose={null}
      position={[0, -1.5, 0]}
      scale={[2.0, 1.8, 2.0]}
      rotation={[0.25, 0, 0]}
      ref={modelRef}
    >
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.polySurface19_Plach_0.geometry}
        material={materials.Plach}
        scale={0.022}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.LP_complite_0.geometry}
        material={materials.complite}
        scale={0.022}
      />
    </group>
  );
}

useGLTF.preload("/models/scene-transformed.glb");
